### ISSUE TITLE
what about debian 12 kernel 6.1+?

### ISSUE THREAD

**Issue by walertos86** [serhepopovych/ixgbe#5]
what about debian 12 kernel 6.1+?

**Comment by walertos86** [comment]
diff -urN ixgbe-5.19.6.orig/src/ixgbe_main.c ixgbe-5.19.6/src/ixgbe_main.c
--- ixgbe-5.19.6.orig/src/ixgbe_main.c  2023-10-24 12:36:37.360629830 +0200
+++ ixgbe-5.19.6/src/ixgbe_main.c       2023-10-24 12:39:15.120760559 +0200
@@ -9869,7 +9869,11 @@
                struct ixgbe_adapter *adapter = q_vector->adapter;

                if (unlikely(skb_tail_pointer(skb) < hdr.network +
+#ifdef VXLAN_HEADROOM
                             VXLAN_HEADROOM))
+#else
+                            vxlan_headroom(0)))
+#endif
                        return;

                /* verify the port is recognized as VXLAN or GENEVE*/

**Comment by serhepopovych** [comment]
New kernels supported in new ixgbe releases made by Intel, not fixing existing version to build on never kernels.

Porting Double-VLAN changes to new version of ixgbe requires git-rebase of all branches on top of new version,
possibly adding fixes/workarounds to build correctly. This approach can be seen in multiple versions supported
via branches on GitHub.

Porting to new ixgbe version will be made on best effort basis. There is no exact dates or time ranges.

**Comment by serhepopovych** [comment]
Fixed in ixgbe-5.19.9.
